networks:
  network:
    external: true

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: